sequenceDiagram
    participant Android
    participant Almacenamiento
    participant API
    participant Web
    participant Individuo
    participant Usuario

    Usuario ->> Web: Registro de individuo a seguir.
    Web ->> Web: Creación de código de seguimiento.
    Web ->> Almacenamiento: Registro de código de seguimiento pendiente.
    Web -->> Usuario: Código de seguimiento.

    Individuo ->> Android: Ingreso de código de seguimiento.
    Android ->> API: Solicitud de registro con código de seguimiento.
    API ->> API: Validacion de solicitud.
    API ->> Almacenamiento: Remoción de código de seguimiento pendiente.
    API ->> Almacenamiento: Registro de usuario.
    API -->> Android: Resultado de registro.
    Android -->> Individuo: Resultado de registro.

    loop Cada 60 segundos
        Android ->> API: Envío de coordenadas provistas por GPS.
        API ->> Almacenamiento: Registro en historial.
    end

    Usuario ->> Web: Consulta de posición de los individuos.
    Web -->> Usuario: Última posición conocida en el mapa.
    loop Cada 60 segundos
        Web ->> API: Consulta de última posición registrada.
        Web ->> Web: Actualización de la posición en mapa.
    end
